AWSTemplateFormatVersion: '2010-09-09'
Description: this is for test ec2
Resources:
  MyEC2res:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0ebfd941bbafe70c6
      InstanceType: t2.micro
      KeyName: satya
      Tags:
        - Key: Name
          Value: SatyaTestEc2
